# Generated by Django 5.0.4 on 2024-04-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_remove_author_quotes'),
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='quotes',
            field=models.ManyToManyField(to='quotes.quote'),
        ),
    ]
