# Generated by Django 5.0.4 on 2024-05-01 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_author_quotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='quotes',
        ),
    ]
