# Generated by Django 5.0.4 on 2024-05-01 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_remove_author_quotes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='fullname',
        ),
    ]
