# Generated by Django 5.0.4 on 2024-05-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0006_author_born_date_author_born_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='born_date',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='author',
            name='born_location',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.CharField(),
        ),
    ]
